lt_num_threads: 4
lt_epsilon: 1e-1
lt_iterations: 64
lt_corr_distance: 3
lt_corr_randomness: 20
lt_sac_rej_thresh: 0.1
lt_min_height: -0.65
lt_leaf_x: 0.5
lt_leaf_y: 0.5
lt_leaf_z: 0.2
lc_num_threads: 4
lc_epsilon: 1e-2
lc_iterations: 128
lc_corr_distance: 10
lc_corr_randomness: 20
lc_sac_rej_thresh: 0.1
lc_resolution: 0.5
lc_type: FGICP
lc_min_height: -0.65
lc_leaf_x: 0.5
lc_leaf_y: 0.5
lc_leaf_z: 0.2

